"""Tests for sprint CLI commands.

Tests the CLI commands added in Story 20.11:
- sprint generate: Generate sprint-status from epic files
- sprint repair: Repair sprint-status from artifact evidence
- sprint validate: Validate sprint-status against artifacts
- sprint sync: Sync sprint-status from state.yaml
"""

import json
import os
from pathlib import Path

import pytest
from typer.testing import CliRunner

from bmad_assist.cli import app
from bmad_assist.cli_utils import (
    EXIT_ERROR,
    EXIT_SUCCESS,
)


@pytest.fixture
def cli_runner() -> CliRunner:
    """Create a CLI test runner."""
    return CliRunner()


@pytest.fixture
def project_dir(tmp_path: Path) -> Path:
    """Create a minimal project directory structure for testing."""
    # Create required directories
    (tmp_path / "docs" / "epics").mkdir(parents=True)
    (tmp_path / "_bmad-output" / "implementation-artifacts" / "stories").mkdir(parents=True)
    (tmp_path / "_bmad-output" / "implementation-artifacts" / "code-reviews").mkdir(parents=True)
    (tmp_path / "_bmad-output" / "implementation-artifacts" / "story-validations").mkdir(
        parents=True
    )
    (tmp_path / ".bmad-assist").mkdir(parents=True)

    return tmp_path


@pytest.fixture
def project_with_epic(project_dir: Path) -> Path:
    """Create a project with a sample epic file."""
    epic_content = """---
epic_num: 1
title: Test Epic
status: in-progress
---

# Epic 1: Test Epic

## Stories

### Story 1.1: First Story
Description of first story.

### Story 1.2: Second Story
Description of second story.

### Story 1.3: Third Story
Description of third story.
"""
    epic_file = project_dir / "docs" / "epics" / "epic-1-test.md"
    epic_file.write_text(epic_content)
    return project_dir


@pytest.fixture
def project_with_sprint_status(project_with_epic: Path) -> Path:
    """Create a project with existing sprint-status.yaml."""
    sprint_content = """# Generated by bmad-assist
generated: 2026-01-01T00:00:00
project: test-project

development_status:
  epic-1: backlog
  1-1-first-story: backlog
  1-2-second-story: in-progress
  1-3-third-story: done
"""
    sprint_path = (
        project_with_epic / "_bmad-output" / "implementation-artifacts" / "sprint-status.yaml"
    )
    sprint_path.write_text(sprint_content)
    return project_with_epic


@pytest.fixture
def project_with_artifacts(project_with_sprint_status: Path) -> Path:
    """Create a project with story artifacts for evidence-based inference."""
    # Create story file for 1-1
    story_1_1 = (
        project_with_sprint_status
        / "_bmad-output"
        / "implementation-artifacts"
        / "stories"
        / "1-1-first-story.md"
    )
    story_1_1.write_text("""---
title: First Story
---

# Story 1.1: First Story

Status: done

Description of first story.
""")

    # Create code review for 1-2 (synthesis = master review)
    review_1_2 = (
        project_with_sprint_status
        / "_bmad-output"
        / "implementation-artifacts"
        / "code-reviews"
        / "synthesis-1-2.md"
    )
    review_1_2.write_text("""# Code Review Synthesis for 1-2

Story is ready.
""")

    # Create story file for 1-3 but no code review
    story_1_3 = (
        project_with_sprint_status
        / "_bmad-output"
        / "implementation-artifacts"
        / "stories"
        / "1-3-third-story.md"
    )
    story_1_3.write_text("""---
title: Third Story
---

# Story 1.3: Third Story

Status: in-progress

Description of third story.
""")

    return project_with_sprint_status


@pytest.fixture
def project_with_state(project_with_sprint_status: Path) -> Path:
    """Create a project with state.yaml for sync testing."""
    state_content = """version: 1
current_epic: 1
current_story: '1.2'
current_phase: dev_story
completed_stories:
  - '1.1'
completed_epics: []
created_at: '2026-01-01T00:00:00+00:00'
updated_at: '2026-01-01T00:00:00+00:00'
"""
    state_path = project_with_sprint_status / ".bmad-assist" / "state.yaml"
    state_path.write_text(state_content)
    return project_with_sprint_status


# =============================================================================
# Test: sprint generate command
# =============================================================================


class TestSprintGenerate:
    """Tests for `bmad-assist sprint generate` command."""

    def test_generate_creates_new_file(
        self, cli_runner: CliRunner, project_with_epic: Path
    ) -> None:
        """Test generate creates new sprint-status when file doesn't exist."""
        result = cli_runner.invoke(app, ["sprint", "generate", "--project", str(project_with_epic)])

        # Should succeed
        assert result.exit_code == EXIT_SUCCESS, result.output

        # Sprint-status should be created
        sprint_path = (
            project_with_epic / "_bmad-output" / "implementation-artifacts" / "sprint-status.yaml"
        )
        assert sprint_path.exists()

        # Check content
        content = sprint_path.read_text()
        assert "1-1-first-story" in content
        assert "1-2-second-story" in content
        assert "epic-1" in content

    def test_generate_merges_with_existing(
        self, cli_runner: CliRunner, project_with_sprint_status: Path
    ) -> None:
        """Test generate merges with existing sprint-status."""
        result = cli_runner.invoke(
            app, ["sprint", "generate", "--project", str(project_with_sprint_status)]
        )

        assert result.exit_code == EXIT_SUCCESS, result.output
        assert "Generated" in result.output

    def test_generate_verbose_shows_changes(
        self, cli_runner: CliRunner, project_with_epic: Path
    ) -> None:
        """Test generate --verbose shows detailed changes."""
        result = cli_runner.invoke(
            app, ["sprint", "generate", "--project", str(project_with_epic), "--verbose"]
        )

        assert result.exit_code == EXIT_SUCCESS, result.output
        # Should show table of changes when verbose
        # Note: if no changes, verbose just shows summary

    def test_generate_handles_no_epics(self, cli_runner: CliRunner, project_dir: Path) -> None:
        """Test generate handles project with no epic files gracefully."""
        result = cli_runner.invoke(app, ["sprint", "generate", "--project", str(project_dir)])

        # Should still succeed, just with no entries
        assert result.exit_code == EXIT_SUCCESS, result.output


# =============================================================================
# Test: sprint repair command
# =============================================================================


class TestSprintRepair:
    """Tests for `bmad-assist sprint repair` command."""

    def test_repair_applies_evidence(
        self, cli_runner: CliRunner, project_with_artifacts: Path
    ) -> None:
        """Test repair applies evidence-based inference."""
        result = cli_runner.invoke(
            app, ["sprint", "repair", "--project", str(project_with_artifacts)],
            input="y\n",  # Confirm the overwrite prompt
        )

        assert result.exit_code == EXIT_SUCCESS, result.output
        assert "Repaired" in result.output

    def test_repair_yes_applies_without_prompt(
        self, cli_runner: CliRunner, project_with_artifacts: Path
    ) -> None:
        """Test repair --yes applies changes without prompting."""
        result = cli_runner.invoke(
            app,
            [
                "sprint",
                "repair",
                "--project",
                str(project_with_artifacts),
                "--yes",
            ],
        )

        assert result.exit_code == EXIT_SUCCESS, result.output
        assert "Repaired" in result.output
        assert "Continue?" not in result.output

    def test_repair_dry_run_shows_changes(
        self, cli_runner: CliRunner, project_with_artifacts: Path
    ) -> None:
        """Test repair --dry-run shows changes without applying."""
        # Get original content
        sprint_path = (
            project_with_artifacts
            / "_bmad-output"
            / "implementation-artifacts"
            / "sprint-status.yaml"
        )
        original_content = sprint_path.read_text()

        result = cli_runner.invoke(
            app, ["sprint", "repair", "--project", str(project_with_artifacts), "--dry-run"]
        )

        assert result.exit_code == EXIT_SUCCESS, result.output
        assert "Dry run" in result.output

        # Content should be unchanged
        assert sprint_path.read_text() == original_content

    def test_repair_verbose_shows_details(
        self, cli_runner: CliRunner, project_with_artifacts: Path
    ) -> None:
        """Test repair --verbose shows divergence details."""
        result = cli_runner.invoke(
            app, ["sprint", "repair", "--project", str(project_with_artifacts), "--verbose"],
            input="y\n",  # Confirm the overwrite prompt
        )

        assert result.exit_code == EXIT_SUCCESS, result.output
        # Verbose shows divergence percentage
        assert "Divergence" in result.output or "Repaired" in result.output

    def test_repair_dry_run_verbose(
        self, cli_runner: CliRunner, project_with_artifacts: Path
    ) -> None:
        """Test repair --dry-run --verbose shows change table."""
        result = cli_runner.invoke(
            app,
            [
                "sprint",
                "repair",
                "--project",
                str(project_with_artifacts),
                "--dry-run",
                "--verbose",
            ],
        )

        assert result.exit_code == EXIT_SUCCESS, result.output
        assert "Dry run" in result.output


# =============================================================================
# Test: sprint status command
# =============================================================================


class TestSprintStatus:
    """Tests for `bmad-assist sprint status` command."""

    def test_status_summarizes_sprint_and_recommends_next_story(
        self, cli_runner: CliRunner, project_with_sprint_status: Path
    ) -> None:
        """Test status prints counts and BMAD next action recommendation."""
        result = cli_runner.invoke(
            app, ["sprint", "status", "--project", str(project_with_sprint_status)]
        )

        assert result.exit_code == EXIT_SUCCESS, result.output
        assert "Sprint Status" in result.output
        assert "Stories: backlog 1, ready-for-dev 0, in-progress 1" in result.output
        assert "Next Recommendation: dev-story (1-2-second-story)" in result.output

    def test_status_json_output(
        self, cli_runner: CliRunner, project_with_sprint_status: Path
    ) -> None:
        """Test status --format=json returns machine-readable workflow data."""
        result = cli_runner.invoke(
            app,
            [
                "sprint",
                "status",
                "--project",
                str(project_with_sprint_status),
                "--format",
                "json",
            ],
        )

        assert result.exit_code == EXIT_SUCCESS, result.output

        data = json.loads(result.stdout)
        assert data["story_counts"]["in-progress"] == 1
        assert data["story_counts"]["backlog"] == 1
        assert data["next"]["workflow_id"] == "dev-story"
        assert data["next"]["story_id"] == "1-2-second-story"
        assert data["entry_count"] == 4

    def test_status_recommends_retrospective_when_all_stories_done(
        self, cli_runner: CliRunner, project_with_sprint_status: Path
    ) -> None:
        """Test status recommends optional retrospective after story work completes."""
        sprint_path = (
            project_with_sprint_status
            / "_bmad-output"
            / "implementation-artifacts"
            / "sprint-status.yaml"
        )
        sprint_path.write_text(
            """# Generated by bmad-assist
generated: 2026-01-01T00:00:00
project: test-project

development_status:
  epic-1: done
  1-1-first-story: done
  1-2-second-story: done
  epic-1-retrospective: optional
"""
        )

        result = cli_runner.invoke(
            app, ["sprint", "status", "--project", str(project_with_sprint_status)]
        )

        assert result.exit_code == EXIT_SUCCESS, result.output
        assert "Next Recommendation: retrospective (epic-1-retrospective)" in result.output

    def test_status_handles_mixed_numeric_and_module_story_keys(
        self, cli_runner: CliRunner, project_with_sprint_status: Path
    ) -> None:
        """Test status sorting supports numeric epics and module-prefixed stories."""
        sprint_path = (
            project_with_sprint_status
            / "_bmad-output"
            / "implementation-artifacts"
            / "sprint-status.yaml"
        )
        sprint_path.write_text(
            """# Generated by bmad-assist
generated: 2026-01-01T00:00:00
project: test-project

development_status:
  epic-1: in-progress
  1-1-first-story: done
  testarch-1-configure-guardrails: backlog
  1-2-second-story: in-progress
"""
        )

        result = cli_runner.invoke(
            app, ["sprint", "status", "--project", str(project_with_sprint_status)]
        )

        assert result.exit_code == EXIT_SUCCESS, result.output
        assert "Next Recommendation: dev-story (1-2-second-story)" in result.output

    def test_status_uses_first_story_number_when_slug_contains_digits(
        self, cli_runner: CliRunner, project_with_sprint_status: Path
    ) -> None:
        """Test ADR-style numeric slug segments do not produce false orphan warnings."""
        sprint_path = (
            project_with_sprint_status
            / "_bmad-output"
            / "implementation-artifacts"
            / "sprint-status.yaml"
        )
        sprint_path.write_text(
            """# Generated by bmad-assist
generated: 2026-01-01T00:00:00
project: test-project

development_status:
  epic-8: in-progress
  8-1-replace-adr-023-placeholder-tests: done
  8-2-replace-adr-040-placeholder-tests: in-progress
"""
        )

        result = cli_runner.invoke(
            app,
            [
                "sprint",
                "status",
                "--project",
                str(project_with_sprint_status),
                "--format",
                "json",
            ],
        )

        assert result.exit_code == EXIT_SUCCESS, result.output

        data = json.loads(result.stdout)
        assert data["next"]["story_id"] == "8-2-replace-adr-040-placeholder-tests"
        assert not any("Orphaned story detected" in risk for risk in data["risks"])

    def test_status_missing_sprint_status(
        self, cli_runner: CliRunner, project_dir: Path
    ) -> None:
        """Test status fails gracefully when sprint-status is missing."""
        result = cli_runner.invoke(app, ["sprint", "status", "--project", str(project_dir)])

        assert result.exit_code == EXIT_ERROR
        assert "Sprint-status not found" in result.output

    def test_status_invalid_format(
        self, cli_runner: CliRunner, project_with_sprint_status: Path
    ) -> None:
        """Test status rejects unsupported output formats."""
        result = cli_runner.invoke(
            app,
            ["sprint", "status", "--project", str(project_with_sprint_status), "--format", "xml"],
        )

        assert result.exit_code == EXIT_ERROR
        assert "Invalid --format" in result.output


# =============================================================================
# Test: sprint validate command
# =============================================================================


class TestSprintValidate:
    """Tests for `bmad-assist sprint validate` command."""

    def test_validate_no_discrepancies(
        self, cli_runner: CliRunner, project_with_sprint_status: Path
    ) -> None:
        """Test validate returns 0 when no ERROR discrepancies."""
        # First repair to ensure consistency
        cli_runner.invoke(
            app,
            [
                "sprint",
                "repair",
                "--project",
                str(project_with_sprint_status),
                "--yes",
            ],
        )

        result = cli_runner.invoke(
            app, ["sprint", "validate", "--project", str(project_with_sprint_status)]
        )

        # Should succeed if only WARN or no discrepancies
        # Note: exact exit code depends on state of artifacts
        assert result.exit_code in (EXIT_SUCCESS, EXIT_ERROR)

    def test_validate_reports_errors(
        self, cli_runner: CliRunner, project_with_artifacts: Path
    ) -> None:
        """Test validate reports ERROR discrepancies."""
        # Manually create a discrepancy: sprint says 'done' but no master review
        # 1-1 has Status: done in story file but no master review
        # This shouldn't be an error since explicit Status wins

        result = cli_runner.invoke(
            app, ["sprint", "validate", "--project", str(project_with_artifacts)]
        )

        # Check output contains discrepancy info or success
        assert result.exit_code in (EXIT_SUCCESS, EXIT_ERROR)

    def test_validate_json_output(
        self, cli_runner: CliRunner, project_with_sprint_status: Path
    ) -> None:
        """Test validate --format=json produces valid JSON."""
        result = cli_runner.invoke(
            app,
            [
                "sprint",
                "validate",
                "--project",
                str(project_with_sprint_status),
                "--format",
                "json",
            ],
        )

        # Parse JSON output - extract JSON object from output
        # (may contain log messages before the JSON when run with other tests)
        output = result.stdout
        json_start = output.find("{")
        if json_start == -1:
            pytest.fail(f"No JSON object found in output: {output}")

        try:
            data = json.loads(output[json_start:])
            assert "success" in data
            assert "exit_code" in data
            assert "summary" in data
            assert "discrepancies" in data
        except json.JSONDecodeError:
            pytest.fail(f"Invalid JSON output: {output[json_start:]}")

    def test_validate_reports_epic_teardown_drift_as_error(
        self, cli_runner: CliRunner, project_dir: Path
    ) -> None:
        """Test validate fails closed when runtime state advances past incomplete teardown."""
        (project_dir / "docs" / "epics" / "epic-7-observability.md").write_text(
            """---
epic_num: 7
title: Observability
status: in-progress
---

# Epic 7: Observability

## Stories

### Story 7.1: Instrumentation
Description.

### Story 7.2: Dashboards
Description.

### Story 7.3: Review Hardening
Description.
"""
        )
        (project_dir / "docs" / "epics" / "epic-8-next.md").write_text(
            """---
epic_num: 8
title: Next Epic
status: backlog
---

# Epic 8: Next Epic

## Stories

### Story 8.1: Next Story
Description.
"""
        )
        (
            project_dir / "_bmad-output" / "implementation-artifacts" / "sprint-status.yaml"
        ).write_text(
            """# Generated by bmad-assist
generated: 2026-04-22T00:00:00
project: epic-7-hardening

development_status:
  epic-7: in-progress
  7-1-instrumentation: done
  7-2-dashboards: done
  7-3-review-hardening: done
  epic-7-retrospective: in-progress
  epic-8: backlog
  8-1-next-story: backlog
"""
        )
        (project_dir / ".bmad-assist" / "state.yaml").write_text(
            """version: 1
current_epic: 8
current_story: '8.1'
current_phase: create_story
completed_stories:
  - '7.1'
  - '7.2'
  - '7.3'
completed_epics:
  - 7
created_at: '2026-04-22T00:00:00+00:00'
updated_at: '2026-04-22T00:00:00+00:00'
"""
        )

        result = cli_runner.invoke(
            app,
            ["sprint", "validate", "--project", str(project_dir), "--format", "json"],
        )

        assert result.exit_code == EXIT_ERROR, result.output

        output = result.stdout
        json_start = output.find("{")
        if json_start == -1:
            pytest.fail(f"No JSON object found in output: {output}")

        data = json.loads(output[json_start:])
        assert data["success"] is False
        assert data["summary"]["error_count"] >= 1

        loop_state = next((d for d in data["discrepancies"] if d["key"] == "loop-state"), None)
        assert loop_state is not None, data["discrepancies"]
        assert loop_state["sprint_status"] == "current state"
        assert "retrospective" in loop_state["reason"] or "durable" in loop_state["reason"]
        assert loop_state["evidence"].endswith(".bmad-assist/state.yaml")

    def test_validate_missing_sprint_status(self, cli_runner: CliRunner, project_dir: Path) -> None:
        """Test validate fails gracefully when sprint-status missing."""
        result = cli_runner.invoke(app, ["sprint", "validate", "--project", str(project_dir)])

        assert result.exit_code == EXIT_ERROR
        assert "not found" in result.output.lower() or "Sprint-status" in result.output

    def test_validate_verbose_shows_evidence(
        self, cli_runner: CliRunner, project_with_artifacts: Path
    ) -> None:
        """Test validate --verbose shows evidence details."""
        result = cli_runner.invoke(
            app, ["sprint", "validate", "--project", str(project_with_artifacts), "--verbose"]
        )

        # Should include either success message or evidence details
        assert result.exit_code in (EXIT_SUCCESS, EXIT_ERROR)

    def test_validate_invalid_format(
        self, cli_runner: CliRunner, project_with_sprint_status: Path
    ) -> None:
        """Test validate with invalid format fails."""
        result = cli_runner.invoke(
            app,
            ["sprint", "validate", "--project", str(project_with_sprint_status), "--format", "xml"],
        )

        assert result.exit_code == EXIT_ERROR
        assert "Invalid --format" in result.output


# =============================================================================
# Test: sprint sync command
# =============================================================================


class TestSprintSync:
    """Tests for `bmad-assist sprint sync` command."""

    def test_sync_updates_sprint_status(
        self, cli_runner: CliRunner, project_with_state: Path
    ) -> None:
        """Test sync updates sprint-status from state.yaml."""
        result = cli_runner.invoke(app, ["sprint", "sync", "--project", str(project_with_state)])

        assert result.exit_code == EXIT_SUCCESS, result.output
        assert "Synced" in result.output

    def test_sync_missing_state(
        self, cli_runner: CliRunner, project_with_sprint_status: Path
    ) -> None:
        """Test sync fails gracefully when state.yaml missing."""
        result = cli_runner.invoke(
            app, ["sprint", "sync", "--project", str(project_with_sprint_status)]
        )

        assert result.exit_code == EXIT_ERROR
        assert "state.yaml not found" in result.output

    def test_sync_verbose_shows_skipped(
        self, cli_runner: CliRunner, project_with_state: Path
    ) -> None:
        """Test sync --verbose shows skipped keys."""
        result = cli_runner.invoke(
            app, ["sprint", "sync", "--project", str(project_with_state), "--verbose"]
        )

        assert result.exit_code == EXIT_SUCCESS, result.output


# =============================================================================
# Test: Common options
# =============================================================================


class TestSprintCommonOptions:
    """Tests for common options across sprint commands."""

    def test_project_option(self, cli_runner: CliRunner, project_with_epic: Path) -> None:
        """Test --project option works for all commands."""
        # Test with explicit project path
        result = cli_runner.invoke(app, ["sprint", "generate", "-p", str(project_with_epic)])
        assert result.exit_code == EXIT_SUCCESS, result.output

    def test_invalid_project_path(self, cli_runner: CliRunner) -> None:
        """Test commands fail gracefully with invalid project path."""
        result = cli_runner.invoke(app, ["sprint", "generate", "--project", "/nonexistent/path"])
        assert result.exit_code == EXIT_ERROR
        assert "not found" in result.output.lower()

    def test_verbose_flag_short(self, cli_runner: CliRunner, project_with_epic: Path) -> None:
        """Test -v short form for verbose flag."""
        result = cli_runner.invoke(app, ["sprint", "generate", "-p", str(project_with_epic), "-v"])
        assert result.exit_code == EXIT_SUCCESS, result.output


# =============================================================================
# Test: Help output
# =============================================================================


@pytest.mark.skipif(os.environ.get("CI") == "true", reason="Rich/Typer help rendering unreliable in CI")
class TestSprintHelp:
    """Tests for sprint command help output."""

    def test_sprint_help(self, cli_runner: CliRunner, cli_isolated_env: Path) -> None:
        """Test sprint --help shows all subcommands."""
        result = cli_runner.invoke(app, ["sprint", "--help"])

        assert result.exit_code == 0
        assert "status" in result.output
        assert "generate" in result.output
        assert "repair" in result.output
        assert "validate" in result.output
        assert "sync" in result.output

    def test_status_help(self, cli_runner: CliRunner, cli_isolated_env: Path) -> None:
        """Test sprint status --help shows options."""
        result = cli_runner.invoke(app, ["sprint", "status", "--help"])

        assert result.exit_code == 0
        assert "--project" in result.output
        assert "--format" in result.output

    def test_generate_help(self, cli_runner: CliRunner, cli_isolated_env: Path) -> None:
        """Test sprint generate --help shows options."""
        result = cli_runner.invoke(app, ["sprint", "generate", "--help"])

        assert result.exit_code == 0
        assert "--project" in result.output
        assert "--verbose" in result.output

    def test_repair_help(self, cli_runner: CliRunner, cli_isolated_env: Path) -> None:
        """Test sprint repair --help shows options."""
        result = cli_runner.invoke(app, ["sprint", "repair", "--help"])

        assert result.exit_code == 0
        assert "--project" in result.output
        assert "--verbose" in result.output
        assert "--dry-run" in result.output
        assert "--yes" in result.output

    def test_validate_help(self, cli_runner: CliRunner, cli_isolated_env: Path) -> None:
        """Test sprint validate --help shows options."""
        result = cli_runner.invoke(app, ["sprint", "validate", "--help"])

        assert result.exit_code == 0
        assert "--project" in result.output
        assert "--verbose" in result.output
        assert "--format" in result.output

    def test_sync_help(self, cli_runner: CliRunner, cli_isolated_env: Path) -> None:
        """Test sprint sync --help shows options."""
        result = cli_runner.invoke(app, ["sprint", "sync", "--help"])

        assert result.exit_code == 0
        assert "--project" in result.output
        assert "--verbose" in result.output
